# Ensures postponed evaluation of type annotations.
# Instead of evaluating type hints immediately, Python stores them as strings.
# This avoids issues with forward references and is commonly used in modern Python projects.
from __future__ import annotations

# Converts dataclass objects into dictionaries.
# We'll use this later to expose the current state in JSON/dict form.
from dataclasses import asdict, dataclass, field

# Any is used when the value can be of any Python type.
# Useful for metadata where we don't know beforehand what will be stored.
from typing import Any


# ------------------------------------------------------------------------------
# SupervisorState
# ------------------------------------------------------------------------------
# This dataclass represents the COMPLETE shared state of the Supervisor.
#
# Think of it as the "memory" or "blackboard" that every node in the
# orchestration graph can read from and write to.
#
# Instead of passing many variables between nodes,
# we pass ONE shared state object.
#
# Later, every LangGraph node will receive this state,
# modify it, and return it.
# ------------------------------------------------------------------------------

@dataclass
class SupervisorState:

    # --------------------------------------------------------------------------
    # The original user query.
    #
    # Example:
    # "Write a LinkedIn post about Retrieval-Augmented Generation."
    #
    # Every node can access this.
    # --------------------------------------------------------------------------
    query: str = ""

    # --------------------------------------------------------------------------
    # Stores which route the Supervisor selected.
    #
    # Examples:
    #
    # "rag"
    # "web"
    # "twin_writer"
    #
    # This is useful for debugging and evaluation.
    # --------------------------------------------------------------------------
    route: str = ""

    # --------------------------------------------------------------------------
    # Stores previous conversation messages.
    #
    # Example:
    #
    # [
    #   {"role":"user","content":"Hello"},
    #   {"role":"assistant","content":"Hi!"}
    # ]
    #
    # This provides short-term conversational memory.
    #
    # field(default_factory=list)
    #
    # IMPORTANT:
    # Never use [] directly because Python would reuse
    # the SAME list across multiple SupervisorState objects.
    #
    # default_factory creates a NEW empty list every time.
    # --------------------------------------------------------------------------
    conversation_history: list[dict[str, str]] = field(default_factory=list)

    # --------------------------------------------------------------------------
    # Stores the retrieved context returned by the RAG agent.
    #
    # Example:
    #
    # "Chunk 1...
    #
    # Chunk 2...
    #
    # Chunk 3..."
    #
    # Twin Writer or Validator may later use this.
    # --------------------------------------------------------------------------
    retrieved_context: str = ""

    # --------------------------------------------------------------------------
    # Stores results returned from a future Web Agent.
    #
    # Example:
    #
    # [
    #     {
    #         "title": "...",
    #         "url": "...",
    #         "content":"..."
    #     }
    # ]
    #
    # Again, default_factory creates a NEW list each time.
    # --------------------------------------------------------------------------
    web_results: list[dict[str, Any]] = field(default_factory=list)

    # --------------------------------------------------------------------------
    # Final answer generated by whichever agent was selected.
    #
    # Initially empty.
    #
    # Later
    #
    # Supervisor
    # ↓
    # RAG
    # ↓
    # answer = "..."
    # --------------------------------------------------------------------------
    answer: str = ""

    # --------------------------------------------------------------------------
    # Generic metadata.
    #
    # This is intentionally flexible.
    #
    # Later you might store:
    #
    # confidence score
    # latency
    # retrieval score
    # citations
    # token count
    #
    # Example:
    #
    # {
    #     "confidence":0.91,
    #     "latency":1.2,
    #     "route":"rag"
    # }
    # --------------------------------------------------------------------------
    metadata: dict[str, Any] = field(default_factory=dict)

    # --------------------------------------------------------------------------
    # Counts how many failures occurred during execution.
    #
    # Useful for:
    #
    # Circuit Breakers
    #
    # Retry Logic
    #
    # Fallback Routing
    #
    # Example:
    #
    # RAG failed
    #
    # failure_count += 1
    #
    # If failure_count > threshold
    #
    # → use Web Agent
    # --------------------------------------------------------------------------
    failure_count: int = 0


# ------------------------------------------------------------------------------
# InMemorySupervisorState
# ------------------------------------------------------------------------------
#
# This class is a VERY SIMPLE in-memory state manager.
#
# Instead of creating new state objects everywhere,
# we keep ONE shared state object.
#
# Think of this as a tiny in-memory database.
#
# Later this could be replaced by:
#
# Redis
# PostgreSQL
# MongoDB
#
# for multi-user deployments.
# ------------------------------------------------------------------------------

class InMemorySupervisorState:
    """Simple in-memory shared state for orchestration flows."""

    def __init__(self) -> None:

        # Create ONE SupervisorState object.

        # Initially everything is empty.

        # query = ""

        # route = ""

        # answer = ""

        self._state = SupervisorState()

    # --------------------------------------------------------------------------
    # Returns the current shared state.
    #
    # Every node can call:
    #
    # state = shared_supervisor_state.get()
    #
    # and read whatever information is currently stored.
    # --------------------------------------------------------------------------
    def get(self) -> SupervisorState:
        return self._state

    # --------------------------------------------------------------------------
    # Updates one or more fields in the shared state.
    #
    # Example:
    #
    # update(route="rag")
    #
    # update(answer="...")
    #
    # update(
    #     route="rag",
    #     answer="..."
    # )
    #
    # kwargs means "accept any named arguments".
    # --------------------------------------------------------------------------
    def update(self, **kwargs: Any) -> SupervisorState:

        # Loop over every field passed to update().
        #
        # Example:
        #
        # route="rag"
        #
        # answer="..."
        #
        for key, value in kwargs.items():

            # Safety check.
            #
            # Prevent accidental updates like:
            #
            # update(routes="rag")
            #
            # which would silently create bugs.
            #
            if not hasattr(self._state, key):
                raise AttributeError(f"Invalid state field: {key}")

            # Dynamically set the attribute.
            #
            # Equivalent to:
            #
            # self._state.route = "rag"
            #
            setattr(self._state, key, value)

        # Return updated state.
        return self._state

    # --------------------------------------------------------------------------
    # Clears the entire conversation state.
    #
    # Useful when:
    #
    # User starts a new conversation.
    #
    # Session expires.
    #
    # We want a clean state.
    # --------------------------------------------------------------------------
    def reset(self) -> SupervisorState:

        # Replace current state with a brand-new object.
        self._state = SupervisorState()

        return self._state

    # --------------------------------------------------------------------------
    # Converts the dataclass into a normal Python dictionary.
    #
    # Example:
    #
    # {
    #     "query":"...",
    #     "route":"rag",
    #     "answer":"..."
    # }
    #
    # Useful for:
    #
    # Logging
    #
    # Debugging
    #
    # Returning JSON through FastAPI
    # --------------------------------------------------------------------------
    def to_dict(self) -> dict[str, Any]:

        # asdict() recursively converts dataclasses into dictionaries.
        return asdict(self._state)


# ------------------------------------------------------------------------------
# Global Singleton
# ------------------------------------------------------------------------------
#
# Create ONE shared state manager.
#
# Every module imports THIS object.
#
# Example:
#
# from state import shared_supervisor_state
#
# state = shared_supervisor_state.get()
#
# This behaves like one shared memory object for the entire application.
#
# NOTE:
#
# This is perfectly fine for local development and learning.
#
# In production (multiple users), this should eventually be replaced
# with session-specific state stored in Redis, a database,
# or LangGraph's checkpointing mechanism.
# ------------------------------------------------------------------------------

shared_supervisor_state = InMemorySupervisorState()